baseURL: https://blog.pathos.page
title: pathos.page
theme: ananke
paginate: 10

defaultContentLanguage: zh

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: false
googleAnalytics: ""

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

languages:
  zh:
    contentDir: content/zh
    languageName: 中文
    weight: 2
    DateFormat: "2006 January 2"
    profileMode:
      enabled: false
      imageUrl: "/profile_avatar.webp"
      imageWidth: 150
      imageHeight: 150
      title: 曹 历鑫
      subtitle: 在城市的肋骨间，感受一成不变的节拍
      buttons:
        - name: 博文
          url: posts
        - name: 出版物
          url: projects
    label:
      text: pathos.page
    menu:
      main:
        - identifier: search
          name: 搜索
          url: /search/
          weight: 3
        - identifier: archives
          name: 归档
          url: /archives/
          weight: 1
        - identifier: tags
          name: 标签
          url: /tags/
          weight: 2
        - identifier: about
          name: 关于
          url: /about/
          weight: 5

params:
  gtm_id: ""
  env: production
  title: pathos.page
  description: 思想 / 思享 / 四向
  keywords: [ 博客 ]
  author: pathos
  images: [ "https://images.unsplash.com/photo-1510843572979-e4b9e790fdd7?auto=format&fit=crop&w=720&q=80" ]

  defaultTheme: auto # dark, light
  disableThemeToggle: false
  displayFullLangName: true

  ShowReadingTime: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    favicon: "/favicon.ico"

  socialIcons:
    - name: github
      url: ""
    - name: twitter
      url: ""
    - name: email
      url: "mailto:kmt007@outlook.com"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  #  editPost:
  #    URL: "https://github.com/lexcao/lexcao.github.io/content"
  #    Text: "Suggest Changes" # edit text
  #    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: [ "title", "permalink", "summary", "content" ]

taxonomies:
  tag: tags
